document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '  <head>\n' );
document.write( '    <meta charset=\"utf-8\">\n' );
document.write( '    <title>UNICEF</title>\n' );
document.write( '    <style>\n' );
document.write( '      #nz {\n' );
document.write( '        background: rgba(102, 102, 102, 0.5);\n' );
document.write( '        width: 100%;\n' );
document.write( '        height: 100%;\n' );
document.write( '        position: absolute;\n' );
document.write( '        top: 0;\n' );
document.write( '        left: 0;\n' );
document.write( '        display: none;\n' );
document.write( '      }\n' );
document.write( '      #w {\n' );
document.write( '        width: 430px;\n' );
document.write( '        height: 87%;\n' );
document.write( '        text-align: center;\n' );
document.write( '        padding: 5px;\n' );
document.write( '        border: 3px solid #1db0ef;\n' );
document.write( '        border-radius: 10px;\n' );
document.write( '        color: #0000cc;\n' );
document.write( '        position: absolute;\n' );
document.write( '        top: 0;\n' );
document.write( '        right: 0;\n' );
document.write( '        bottom: 0;\n' );
document.write( '        left: 0;\n' );
document.write( '        margin: auto;\n' );
document.write( '        background: #1db0ef;\n' );
document.write( '      }\n' );
document.write( '      #nz:target {display: block;}\n' );
document.write( '      .close {\n' );
document.write( '        display: inline-block;\n' );
document.write( '        border: 0px solid #0000cc;\n' );
document.write( '        color: #0000cc;\n' );
document.write( '        padding: 0 5px;\n' );
document.write( '        margin: 10px;\n' );
document.write( '        text-decoration: none;\n' );
document.write( '        background: #1db0ef;\n' );
document.write( '        font-size: 14pt;\n' );
document.write( '        cursor:pointer;\n' );
document.write( '      }\n' );
document.write( '      a {     \n' );
document.write( '        text-decoration: none;             \n' );
document.write( '      }\n' );
document.write( '      .close:hover {background: #1db0ef;}\n' );
document.write( '    </style>\n' );
document.write( '  </head>\n' );
document.write( ' \n' );
document.write( '  <body>\n' );
document.write( '   \n' );
document.write( '    <div id=\"nz\">\n' );
document.write( '      <div id=\"w\">\n' );
document.write( '        <iframe src=\"/u-nz.html\" width=\"100%\" height=\"90%\" style=\"border: 2px solid #1db0ef;\"></iframe><a href=\"#\" class=\"close\" style=\"color:#666666;\">X</a>\n' );
document.write( '        \n' );
document.write( '      </div>\n' );
document.write( '    </div>\n' );
document.write( '     \n' );
document.write( '    <button style=\"width:120px;height:40px;background-color:#000000;bordercolor:#6E838B;border-radius:12px;\" type=\"button\" class=\"write-btn btn btn-xs btn-primary border disabled\" id=\'btn_5\'><a href=\"#nz\" style=\"color:#CCDCE6\">New Zealand</a></button>\n' );
document.write( ' \n' );
document.write( '  </body>\n' );
document.write( '</html>\n' );